#!/bin/bash

which busybox 1>/dev/null || { echo "busybox not found"; return 1; }

## base 64 encode wrapper
b64e(){
    busybox base64
}

## base 64 decode wrapper
b64d(){
    busybox base64 -d
}

## put a file into a var 1:1 naming
fileToVar(){
    $1=$(b64e <$1)
}

## put a var into a file 1:1 naming
varToFile(){
    echo "$1" | b64d >"$1"
}
